---
language: python
python: "3.6"
dist: trusty
sudo: false
group: beta
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - pip install tox | cat

script:
  - tox

notifications:
  on_failure: never
  email: false
