---
- hosts: all
  become: yes
  become_user: root
  handlers:
  - name: Update initramfs
    command: /usr/sbin/update-initramfs -u

  - name: Update GRUB
    command: /usr/sbin/update-grub

  tasks:
  - assert:
      that:
      - ansible_pkg_mgr == 'apt'

  - name: Add libdvdcss APT repository key
    apt_key:
        url: http://download.videolan.org/pub/debian/videolan-apt.asc
        state: present

  - name: Add libdvdcss APT repository
    with_items:
        - deb
        - deb-src
    apt_repository:
        repo: '{{ item }} http://download.videolan.org/pub/debian/stable/ /'
        state: present
        update_cache: yes

  - name: APT install
    with_items:
    - plymouth
    - initramfs-tools
    - libdvdcss2
    apt:
      name: '{{ item }}'
      state: present
      update_cache: yes
      cache_valid_time: 3600
  - name: Configure Plymouth
    ini_file:
      dest: /etc/plymouth/plymouthd.conf
      section: Daemon
      option: Theme
      value: spinner
    register: configure_plymouth

  - name: Configure GRUB
    with_dict:
      GRUB_TIMEOUT: 1
      GRUB_CMDLINE_LINUX_DEFAULT: 'quiet cgroup_enable=memory splash allow-discards root_trim=yes swapaccount=1'
    lineinfile:
      dest: /etc/default/grub
      line: '{{ item.key }}="{{ item.value }}"'
      regexp: '^{{ item.key }}='
      state: present
    register: configure_grub

  - name: Make /tmp tmpfs mount
    mount:
      fstype: tmpfs
      name: /tmp
      src: none
      state: present
