---
- hosts: all
  become: false
  vars:
      apt:
          - ansible
          - apache2-utils
          - apt-listchanges
          - apt-xapian-index
          - awscli
          - bijiben
          - bluez-firmware
          - brasero
          - capistrano
          - cargo
          - clojure1.6
          - cmake
          - containerd
          - cryptsetup
          - deborphan
          - deja-dup
          - dh-make
          - dnsmasq
          - dnsutils
          - docker-compose
          - dos2unix
          - dvd+rw-tools
          - easy-rsa
          - epiphany-browser
          - expect
          - fabric
          - file-roller
          - firmware-intel-sound
          - firmware-iwlwifi
          - firmware-linux
          - flake8
          - flatpak-builder
          - ftp
          - geary
          - ghex
          - git-annex
          - git-buildpackage
          - gnome-boxes
          - gnome-calendar
          - gnome-clocks
          - gnome-core
          - gnome-documents
          - gnome-logs
          - gnome-maps
          - gnome-music
          - gnome-photos
          - gnome-shell-extensions-gpaste
          - gnome-software
          - gnome-todo
          - gnome-weather
          - golang
          - grub-efi-amd64
          - gstreamer1.0-vaapi
          - hunspell
          - hyphen-en-us
          - iputils-ping
          - keepass2
          - kpcli
          - libnss-resolve
          - libpam-mount
          - libreoffice-pdfimport
          - linux-image-amd64
          - liferea
          - luarocks
          - meld
          - mythes-en-us
          - netcat-openbsd
          - network-manager-gnome
          - network-manager-pptp-gnome
          - nodejs-legacy
          - npm
          - ostree
          - pandoc
          - pelican
          - plymouth-themes
          - polari
          - printer-driver-all
          - pry
          - python3-pip
          - python3-venv
          - python-dev
          - python-parse
          - python-pip
          - python-sh
          - python-virtualenv
          - reprepro
          - resolvconf
          - simple-scan
          - strongswan-nm
          - task-english
          - task-hebrew
          - task-hebrew-desktop
          - task-hebrew-gnome-desktop
          - task-gnome-desktop
          - task-laptop
          - task-print-server
          - task-ssh-server
          - telnet
          - texlive-latex-base
          - texlive-fonts-recommended
          - texlive-luatex
          - time
          - tmux
          - tox
          - udftools
          - ufw
          - uidmap
          - vcdimager
          - vagrant
          - vim-nox
          - vinagre
          - virtualbox-qt
          - xdg-user-dirs 
      go:
          - github.com/giantswarm/semver-bump
          - github.com/nishanths/license
      gem:
      npm:
          - yo
          - grunt-cli
          - gulp
          - webcoach
          - sitespeed.io
      pip:
          - ansible-lint
          - molecule
          - pre-commit
          - proselint
          - testinfra
          - twine
          - bcrypt
          - passlib
      pip3:
      cargo:
          - rustfmt

  tasks:
      - assert:
          that:
              - ansible_pkg_mgr == 'apt'

      - name: apt install
        when: apt is iterable and ansible_pkg_mgr == 'apt'
        become: yes
        become_user: root
        apt:
            name: '{{ apt|join(" ") }}'
            state: latest
            purge: yes
            force: yes
            update_cache: yes
            cache_valid_time: 3600

      - name: go get
        when: go is iterable
        shell: 'go get -u {{ go|join(" ") }}'

      - name: gem install
        when: gem is iterable
        become: yes
        become_user: root
        gem:
            name: '{{ gem|join(" ") }}'
            state: latest

      - name: npm install
        when: npm is iterable
        become: yes
        become_user: root
        npm:
            global: yes
            name: '{{ npm|join(" ") }}'
            state: latest

      - name: pip install
        when: pip is iterable
        become: yes
        become_user: root
        pip:
            name: '{{ pip|join(" ") }}'
            state: latest

      - name: pip3 install
        when: pip3 is iterable
        become: yes
        become_user: root
        pip:
            name: '{{ pip3|join(" ") }}'
            state: latest
            executable: pip3

      - name: cargo install
        when: cargo is iterable
        become: no
        command: '/usr/bin/cargo install {{ cargo|join(" ") }}'
