---
- hosts: all
  become: false
  vars:
      apt:
          - adb
          - apache2-utils
          - apt-listchanges
          - apt-xapian-index
          - bijiben
          - bluez-firmware
          - brasero
          - cargo
          - clojure
          - cmake
          - containerd
          - cryptsetup
          - deborphan
          - deja-dup
          - dh-make
          - dnsmasq
          - dnsutils
          - dos2unix
          - dstat
          - dvd+rw-tools
          - easy-rsa
          - epiphany-browser
          - expect
          - file-roller
          - firmware-intel-sound
          - firmware-iwlwifi
          - firmware-linux
          - flatpak-builder
          - ftp
          - geary
          - ghex
          - git-annex
          - git-buildpackage
          - gnome-boxes
          - gnome-calendar
          - gnome-clocks
          - gnome-core
          - gnome-documents
          - gnome-logs
          - gnome-maps
          - gnome-music
          - gnome-photos
          - gnome-shell-extensions-gpaste
          - gnome-software
          - gnome-todo
          - gnome-weather
          - gnupg2
          - golang
          - gpgv
          - graphviz
          - grub-efi-amd64
          - gstreamer1.0-libav
          - gstreamer1.0-vaapi
          - hunspell
          - hyphen-en-us
          - iputils-ping
          - keepass2
          - kpcli
          - libnss-resolve
          - libnss-systemd
          - libpam-mount
          - libreoffice-pdfimport
          - linux-image-amd64
          - liferea
          - luarocks
          - meld
          - mythes-en-us
          - netcat-openbsd
          - network-manager-gnome
          - network-manager-pptp-gnome
          - nodejs-legacy
          - npm
          - ostree
          - pandoc
          - phantomjs
          - plymouth-themes
          - polari
          - printer-driver-all
          - python3-cffi
          - python3-cryptography
          - python3-pip
          - python3-venv
          - python-cffi
          - python-cryptography
          - python-dev
          - python-pip
          - python-virtualenv
          - reprepro
          - resolvconf
          - ruby-ffi
          - ruby-full
          - screen
          - simple-scan
          - strongswan-nm
          - task-english
          - task-hebrew
          - task-hebrew-desktop
          - task-hebrew-gnome-desktop
          - task-gnome-desktop
          - task-laptop
          - task-print-server
          - task-ssh-server
          - telnet
          - texlive-extra-utils
          - texlive-fonts-recommended
          - texlive-font-utils
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-luatex
          - time
          - tmux
          - tox
          - udftools
          - ufw
          - uidmap
          - vcdimager
          - vagrant
          - vim-nox
          - vinagre
          - virtualbox-qt
          - vlc
          - xdg-user-dirs
      go:
          - github.com/giantswarm/semver-bump
          - github.com/nishanths/license
          - github.com/tmrts/boilr
      gem:
          - bundler
          - capistrano
          - pry
          - rake
          - travis
      npm:
          - yo
          - generator-generator
          - grunt-cli
          - gulp
          - webcoach
          - sitespeed.io
      pip:
          - ansible
          - ansible-container
          - ansible-lint
          - bcrypt
          - boto
          - boto3
          - docker-py
          - molecule
          - netaddr
          - passlib
          - python-vagrant
          - testinfra
      pip3:
          - awscli
          - awslogs
          - docker-compose
          - Fabric3
          - flake8
          - kappa
          - parse
          - pelican
          - piprot
          - pre-commit
          - proselint
          - selenium
          - sh
          #- template
          - tox
          - twine
          - yapf
      cargo:
          - rustfmt

  tasks:
      - name: Assertions
        assert:
          that:
              - ansible_pkg_mgr == 'apt'

      - name: apt install
        when: apt is iterable
        become: yes
        become_user: root
        apt:
            name: '{{ apt }}'
            state: present
            purge: yes
            force: yes
            update_cache: yes
            cache_valid_time: 3600

      - name: go get
        when: go is iterable
        command: 'go get -u {{ go|join(" ") }}'
        register: go_get
        changed_when: "'get' in go_get"

      - name: gem install
        with_items: '{{ gem }}'
        when: gem is iterable
        become: yes
        become_user: root
        gem:
            name: '{{ item }}'
            state: present
            include_dependencies: yes

      - name: npm install
        with_items: '{{ npm }}'
        when: npm is iterable
        become: yes
        become_user: root
        npm:
            global: yes
            name: '{{ item }}'
            state: present

      - name: pip install
        when: pip is iterable
        become: yes
        become_user: root
        pip:
            name: '{{ pip }}'
            state: present

      - name: pip3 install
        when: pip3 is iterable
        become: yes
        become_user: root
        pip:
            name: '{{ pip3 }}'
            state: present
            executable: pip3

      - name: cargo install
        when: cargo is iterable
        become: no
        command: '/usr/bin/cargo install {{ cargo|join(" ") }}'
        register: cargo_install
        failed_when: cargo_install.rc > 0 and not 'already exists in destination' in cargo_install.stderr
        changed_when: cargo_install.rc == 0
