---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Assertions
      assert:
        that:
          - ansible_architecture in [ 'x86_64', 'x86' ]
          - ansible_pkg_mgr == 'apt'

    - name: APT install Flatpak
      apt:
        name: flatpak
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Add Flathub repo
      become: false
      # yamllint disable-line rule:line-length
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user
      changed_when: false

    - name: Install
      become: false
      # yamllint disable-line rule:line-length
      command: flatpak install --user --assumeyes flathub com.slack.Slack
      register: slack_flatpak_install
      changed_when: |
         'Installing' in slack_flatpak_install.stdout
      failed_when: >-
        slack_flatpak_install.rc|int > 0 and
        'already installed' not in slack_flatpak_install.stderr
