---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Add repo key
    apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

  - name: Add repo
    apt_repository:
        repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache: True

  - name: APT install
    apt:
        name: code
        state: present
        install_recommends: False
        update_cache: True
        cache_valid_time: 3600
